parent: classic
name: biedronka
display_name: Biedronka theme
version: 1.0.0
author:
  name: "Studenci Pg"
  email: "pub@biedronka.pg.edu.pl"
  url: "https://localhost:8080"
assets:
  use_parent_assets: true
