version: '3'
services:
  mysql:
    container_name: some-mysql
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    build:
      context: ..
      dockerfile: docker/prestashop/Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: toor
      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
      PS_DOMAIN: localhost:8080
      PS_LANGUAGE: en
      PS_COUNTRY: us
      PS_ENABLE_SSL: 0
      ADMIN_MAIL: makajler@szpont.pl
      ADMIN_PASSWD: password
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
    networks:
      - prestashop_network
    volumes:
      # Use only if needed
      # - ../src/prestashop:/var/www/html
      - ../src/biedronka-theme:/var/www/html/themes/biedronka
networks:
    prestashop_network:
