version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"   # port 8081 lokalnie, żeby nie kolidował z PrestaShop 8080
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: toor
    depends_on:
      - mysql
    networks:
      - prestashop_network

  mysql:
    container_name: some-mysql
    build:
      context: ..
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: prestashop
    mem_limit: 1024M
    cpus: '1.0'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    build:
      context: ..
      dockerfile: docker/prestashop/Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 443:443
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: toor
      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
      PS_DOMAIN: localhost
      PS_LANGUAGE: en
      PS_COUNTRY: us
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: makajler@szpont.pl
      ADMIN_PASSWD: password
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-dev
    mem_limit: 1024M
    cpus: '2.0'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
    networks:
      - prestashop_network
    volumes:
      - prestashop_data:/var/www/html
      # Use only if needed
      # - ../src/prestashop:/var/www/html
      - ../src/themes/biedronka:/var/www/html/themes/biedronka
      - ./certs:/etc/ssl/private:ro
networks:
    prestashop_network:

volumes:
  mysql_data:
    driver: local
  prestashop_data:
    driver: local
